### ISSUE TITLE
JOSS Review: Publish package via conda

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#14]
Since the package already has an environment.yaml file, adding a conda recipe and uploading it to conda forge would be a very nice and rather easy addition.

- [x] Add conda [recipe](https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html) [meta.yaml](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html)
- [x] Move conda related files (environment.yaml, meta.yaml) to dedicated `conda` folder
- [ ] Upload package to [conda-forge](https://conda-forge.org/docs/user/introduction.html)

**Comment by tgoelles** [comment]
It seems like this is not so easy to achieve. Because  "py3rosmsgs" has no conda package.  I also didn't find any equivalent available on conda. 

I set everything up with github actions but this is the bottleneck.

So I think this is not possible at the moment.

**Comment by hechth** [comment]
I see - the message passing can't be done via the pyros package (sorry if this is a dumb question, the ROS world is outside of my domain!).

Another option would be to contact the developer of py3rosmsgs and ask for condafication, but I had a quick look and the package seems to be somewhat automatically generated or so, so I'm not sure how straightforward that will be.

**Comment by tgoelles** [comment]
I merged your PR, but building still failed since py3rosmsgs is not on conda.

see error messages in the github actions run: https://github.com/virtual-vehicle/pointcloudset/runs/3471933863?check_suite_focus=true

How did your build succeed without py3rosmsgs?

**Comment by hechth** [comment]
@tgoelles I didn't do anything regarding that package, setting up the development environment failed on my machine, independent from package building.

**Comment by tgoelles** [comment]
With the switch to rosbags  and their enabling of conda it should no be possible!
https://anaconda.org/conda-forge/rosbags

**Comment by tgoelles** [comment]
Well no open3d is not available on conda anymore: https://github.com/isl-org/Open3D/issues/5272.

Everything else should work, see now branch tg_conda_build

**Comment by tgoelles** [comment]
closing this issue, just support pip for now.
