### ISSUE TITLE
JOSS Review: Refactor tests

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#16]
The suite of tests looks good, but it could actually be made a lot more comprehensive and smaller with the use of [parameterized test cases](https://docs.pytest.org/en/6.2.x/parametrize.html) and [test fixtures](https://docs.pytest.org/en/6.2.x/reference.html#fixtures-api).

**Comment by tgoelles** [comment]
Yes the tests have been improved and made more comprehensive
