### ISSUE TITLE
JOSS Review: Handling large files

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#18]
**Describe the bug**
Plotting large point clouds (>500,000 points) seems to be taking up a lot of RAM (>8gb).

**To Reproduce**
1. Load large point cloud (I can provide an example file)
2. Call plot function.

**Expected behavior**
It should be stated up to which sizes can be handled reasonably or the program should provide options for visualization that make it easier, like random subsampling or spatial subsampling to uniform density.

**Desktop (please complete the following information):**
 - OS: Windows 10 16gb RAM i5 quad core with hyperthreading
 - Version: 0.2.3

**Comment by tgoelles** [comment]
Yes please provide an example file.

The claim with large files was aimed towards large "datasets" of point clouds i.e. large bagfiles. Neverthless, it should also handle large point clouds reasonably well. A possible solution would be to fall back to plotting provided by pyntcloud for larger pointclouds.

**Comment by hechth** [comment]
@tgoelles did you receive the link to the file via email?

**Comment by tgoelles** [comment]
@hechth No, I did not get the link. Please use thomas.goelles@v2c2.at

**Comment by hechth** [comment]
@tgoelles Sorry, I was on vacation. I will share the file again with you, but I think this is a good solution to this!
