### ISSUE TITLE
JOSS Review: Statement of need

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#23]
The statement of need focuses more on the advances in LIDAR technology than the problems in related software - only the fact that the technology is advancing doesn't justify the need for more software.

Why is accessing time-series point cloud data important? Why do the current packages not suffice for this task? How does this package circumvent these problems? How does pointcloudset combine pyntcloud and ROS to provide a better software solution?

Also, can you find any scientific publication for which this software would be beneficial or where you could demonstrate its purpose? Also, for which specific problem (i.e autonomous driving, object detection in point clouds) are you developing the software? If it has no specific purpose, how does it function as a general framework for various applications (clustering, general filtering, feature detection -> dense areas, planes, etc.) and can you give a simple example where such a general framework (in connection with the point cloud series aspect) can be used?

**Comment by birgitschlager** [comment]
I divided the manuscript into three sections: "Emerging Point Cloud Sensor Technologies", "Statement of Need" and "Data Strutcutres of pointcloudset". The section "Emerging Point Cloud Sensor Technologies" lists possible areas of applications such as robotics, geophysics and automotive applications. The section "Statement of Need" focuses more on the difference between existing packages such as  open3d, pyntcloud, pdal and pcl and the pointcloud set package than in the last version of the manuscript. Also, the features of pointcloudset are described in more detail now. Furhtermore, I separated the last paragraph and added a separate section "Data Structures of pointcloudset".
Is it clearer now?
