### ISSUE TITLE
JOSS Review: State of the field

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#24]
Have you had a look at [python-pcl](https://github.com/strawlab/python-pcl)? I personally haven't worked much with PCL, it is quite a beast in C++ so I usually prefer CloudCompare for that, but the python bindings of PCL might be interesting.

**Comment by birgitschlager** [comment]
As far as I saw in the documentation of pcl, it rather focuses on the processing of single point clouds than on time series of point clouds. I added the pcl and its python bindings as references for related packages in the manuscript.
