### ISSUE TITLE
JOSS Review: Conda file environment name

### ISSUE THREAD

**Issue by hechth** [virtual-vehicle/pointcloudset#25]
The name `base` should be avoided since it would install or override the default environment - a name like `pointcloudset` or `pointcloudset-dev` would be a better solution.
https://github.com/virtual-vehicle/pointcloudset/blob/09f7bfe22b11a9fc0ec967c92854f5cf69622529/conda/environment.yml#L1

**Comment by tgoelles** [comment]
changed to pointcloudset
