### ISSUE TITLE
Add support for rosbag2 version 7 

### ISSUE THREAD

**Issue by mrrevillo0815** [virtual-vehicle/pointcloudset#72]
Sadly it is not possible to use the latest .mcap file format.
Here the whole Traceback:

`
Traceback (most recent call last):
  File "/pcd_intensities.py", line 64, in <module>
    pcd = pointcloudset.Dataset.from_file(rosfile_path,topic=topic)
  File "/opt/conda/lib/python3.10/site-packages/pointcloudset/dataset.py", line 114, in from_file
    res = DATASET_FROM_FILE[ext](file_path, ext=ext, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pointcloudset/io/dataset/ros.py", line 117, in dataset_from_ros
    with Reader(bagfile.as_posix()) as reader:
  File "/opt/conda/lib/python3.10/site-packages/rosbags/rosbag2/reader.py", line 105, in __init__
    raise ReaderError(f'Rosbag2 version {ver} not supported; please report issue.')
rosbags.rosbag2.errors.ReaderError: Rosbag2 version 7 not supported; please report issue.
`

If possible, please add the support.

**Comment by mrrevillo0815** [comment]
This happened while using your latest docker image, so please create a new version of it, if possible

It can be fixed by upgrading `rosbags` to `0.9.19`
e.g.: `pip install rosbags -U` while ssh-ing into the image

**Comment by tgoelles** [comment]
@Grisly00 did you encounter this as well? Any ideas how to fix this?

**Comment by Grisly00** [comment]
@tgoelles Have not seen this, but could be that we use an older format of mcap. We use ROS2 humble for recording. I found two rosbags related pip packages in our container if that helps:
```
rosbag2-interfaces                   0.15.8
rosbag2-py                           0.15.8
```

**Comment by mrrevillo0815** [comment]
@tgoelles it is just an issue with the docker image

When installing it locally with pip, pip will install the newest version of rosbags (0.9.20) which fixes the issue. So basically this is a docker only issue.

**Comment by tgoelles** [comment]
Hi, version 0.10.0 should solve this. The docker image is now also less than half the size.
